services:
  - type: web
    name: ustoziya
    env: python
    plan: free
    pythonVersion: 3.11.0
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    startCommand: gunicorn ustoziya_platform.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: ustoziya-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ustoziya.onrender.com,*.onrender.com
      - key: TESSERACT_PATH
        value: /usr/bin/tesseract

databases:
  - name: ustoziya-db
    plan: free
    databaseName: ustoziya
    user: ustoziya

